# Generated by Django 3.2.11 on 2022-04-27 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import google_2fa.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Google2FA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_key', models.CharField(default=google_2fa.models.generate_reserve_key, max_length=12)),
                ('secret', models.CharField(max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_2fa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google 2FA',
                'verbose_name_plural': 'Google 2FA',
            },
        ),
    ]
