# Generated by Django 3.2.11 on 2022-04-27 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('google_2fa', '0002_alter_google2fa_reserve_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='google2fa',
            options={'verbose_name': 'Two Factor Authentication', 'verbose_name_plural': 'Two Factor Authentications'},
        ),
        migrations.AlterField(
            model_name='google2fa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_fa', to=settings.AUTH_USER_MODEL),
        ),
    ]
