# Generated by Django 3.1.1 on 2020-09-21 08:30

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.conf import settings


def set_superuser(apps, schema_editor):
    user_obj = apps.get_model("main", "User")
    user = user_obj(
        id=0,
        username=settings.SUPER_USER_USERNAME,
        email=settings.SUPER_USER_EMAIL,
        first_name='StemSC',
        last_name='Admin',
        is_staff=True,
        is_active=True,
        is_superuser=True,
    )
    user.password = make_password(settings.SUPER_USER_PASSWORD)
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_superuser),
    ]
