# Generated by Django 3.2.11 on 2022-04-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_set_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
