apiVersion: v2
name: templatechart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: 10.16.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled, global.postgresql.enabled
  - name: redis
    version: 16.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled, global.redis.enabled
