name: Push image to DockerHub

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      push:
        default: true
        type: boolean
      context:
        default: "."
        type: string
      tags:
        default: "latest"
        type: string
      dockerfile:
        default: "docker/prod/web/Dockerfile"
        type: string
    secrets:
      docker_hub_username:
        required: true
      docker_hub_password:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_hub_username }}
          password: ${{ secrets.docker_hub_password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.repository }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: ${{ inputs.push }}
          tags: ${{ inputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
