name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    env:
      REPOSITORY: "bandirom/django-template"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "IMAGE_TAG=$REPOSITORY:$RELEASE_VERSION" >> $GITHUB_ENV
          echo "IMAGE_TAG_LATEST=$REPOSITORY:latest" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo ${{ env.IMAGE_TAG }}
          echo ${{ env.IMAGE_TAG_LATEST }}

#      - name: Build the Docker image
#        run: |
#          docker build -t ${{ env.RELEASE_VERSION }} -t $IMAGE_TAG_LATEST -f docker/prod/web/Dockerfile .
#          docker push $IMAGE_TAG
#          docker push $IMAGE_TAG_LATEST
