name: Release

on:
  push:
    tags:
      - "/^v[0-9]+\.[0-9]+\.[0-9]+-.+$/"

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build the Docker image
        run: |
          pwd
